---
- name: Hello World!
  hosts: all
 
  tasks:
    - name: Hello World!
      shell: echo "Hi! Tower is working."
    - name: Ping the servers
      ping:
    - name: debug
      debug:
        msg: "{{ ansible_facts }}"
